package com.hashone.commons.utils

var mLastClickTime: Long = 0L

const val DEFAULT_LANGUAGE = "DEFAULT_LANGUAGE"
const val DEFAULT_LANGUAGE_COUNTY_CODE = "DEFAULT_LANGUAGE_COUNTY_CODE"
const val DEFAULT_LANGUAGE_NAME = "DEFAULT_LANGUAGE_NAME"
const val ACTION_LANGUAGE_CHANGE = "ACTION_LANG_CHANGE"